AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that cleans unconfirmed users from a Cognito User Pool.

Resources:
  lambda:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: lambda.cognito_cleaner.main_handler
      Runtime: python3.10
      CodeUri: cognito_clean/
      Description: Cleans unconfirmed users from a Cognito User Pool.
      MemorySize: 128
      Timeout: 100